AWSTemplateFormatVersion: 2010-09-09
Description: "Creates infrastructure for Thumnbail Creator"

Parameters:
  RawBucketName:
    Type: String
    Default: rawimages
    Description: Enter the name of the Raw Images Bucket

  ThumbnailBucketName:
    Type: String
    Default: thumbnailimages
    Description: Enter the name of the Thumbnail Images Bucket

  ApiGatewayName:
    Type: String
    Default: tcapigateway
    Description: Enter the name of the API Gateway

  CreateThumbnailLambdaVersionFile:
    Type: String
    Description: The file containing the compiled contents for the Lambda

  AnalyzeImageLambdaVersionFile:
    Type: String
    Description: The file containing the compiled contents for the Lambda

Resources:
  ImageUploadTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ImageUploadTopic
      Subscriptions:
        - Endpoint: !GetAtt CreateThumbnailFunction.Arn
          Protocol: lambda
        - Endpoint: !GetAtt AnalyzeImageFunction.Arn
          Protocol: lambda

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RawBucketName
      TopicConfiguration:
        Event: "s3:ObjectCreated:*"
        Topic: !GetAtt ImageUploadTopic.Arn

  CreateThumbnailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: thumbnailcreator-artifacts
        S3Key: !Ref CreateThumbnailLambdaVersionFile
      Handler: CreateThumbnailFunction::Functions.CreateThumbnailFunction::ExecuteAsync
      Runtime: dotnetcore2.1
      Role: !GetAtt AppRole.Arn
      TracingConfig:
        Mode: Active
      Timeout: 300
      Environment:
        Variables:
          ThumbnailBucketName: !Ref ThumbnailBucketName

  AnalyzeImageFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: thumbnailcreator-artifacts
        S3Key: !Ref AnalyzeImageLambdaVersionFile
      Handler: AnalyzeImageFunction::Functions.AnalyzeImageFunction::ExecuteAsync
      Runtime: dotnetcore2.1
      Role: !GetAtt AppRole.Arn
      TracingConfig:
        Mode: Active
      Timeout: 600

  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "tc-s3-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource: "*"
        - PolicyName: "tc-lambda-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:*"
                Resource: "*"
        - PolicyName: "tc-xray-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "xray:*"
                Resource: "*"
        - PolicyName: "tc-logs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"
        - PolicyName: "tc-cloudwatch-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "cloudwatch:*"
                Resource: "*"
      RoleName: tc-role

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ThumbnailBucketName

  ApiGatewayRest:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName
      Description: Api Gateway to enable reading and writing of image data
      BinaryMediaTypes:
        - image/png
      EndpointConfiguration:
        Types:
          - REGIONAL

  BucketApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: !Ref RawBucketName
      RestApiId: !Ref ApiGatewayRest
      ParentId: !GetAtt
        - ApiGatewayRest
        - RootResourceId
    DependsOn:
      - ApiGatewayRest

  BucketItemApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      PathPart: "{item}"
      RestApiId: !Ref ApiGatewayRest
      ParentId: !Ref BucketApiResource

  BucketItemApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRest
      ResourceId: !Ref BucketItemApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      OperationName: SaveImage
      MethodResponses:
        - StatusCode: 201
      RequestParameters:
        method.request.header.Content-Disposition: false
        method.request.header.Content-Type: true
        method.request.path.item: true
      Integration:
        Type: AWS
        Credentials: !GetAtt
          - AppRole
          - Arn
        IntegrationHttpMethod: PUT
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters:
          integration.request.header.Content-Disposition: method.request.header.Content-Disposition
          integration.request.header.Content-Type: method.request.header.Content-Type
          integration.request.path.key: method.request.path.item
        Uri:
          Fn::Join:
            - "/"
            - - "arn:aws:apigateway:us-east-1:s3:path"
              - !Ref RawBucketName
              - "{key}"
        IntegrationResponses:
          - StatusCode: 201

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayRest
      StageName: DefaultDeployment
    DependsOn:
      - ApiGatewayRest
      - BucketItemApiMethod

  DefaultApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGatewayRest
      TracingEnabled: true
      DeploymentId: !Ref ApiGatewayDeployment
